
export const arabicLetters = [
  { symbol: "ا", english: "Alif", sound_path: "/sounds/arabic/Alif.mp3" },
  { symbol: "ب", english: "Baa", sound_path: "/sounds/arabic/Baa.mp3" },
  { symbol: "ت", english: "Taa", sound_path: "/sounds/arabic/Taa.mp3" },
  { symbol: "ث", english: "Thaa", sound_path: "/sounds/arabic/Thaa.mp3" },
  { symbol: "ج", english: "Jeem", sound_path: "/sounds/arabic/Jeem.mp3" },
  { symbol: "ح", english: "Haa", sound_path: "/sounds/arabic/Haa.mp3" },
  { symbol: "خ", english: "Khaa", sound_path: "/sounds/arabic/Khaa.mp3" },
  { symbol: "د", english: "Daal", sound_path: "/sounds/arabic/Daal.mp3" },
  { symbol: "ذ", english: "Dhaal", sound_path: "/sounds/arabic/Dhaal.mp3" },
  { symbol: "ر", english: "Raa", sound_path: "/sounds/arabic/Raa.mp3" },
  { symbol: "ز", english: "Zay", sound_path: "/sounds/arabic/Zay.mp3" },
  { symbol: "س", english: "Seen", sound_path: "/sounds/arabic/Seen.mp3" },
  { symbol: "ش", english: "Sheen", sound_path: "/sounds/arabic/Sheen.mp3" },
  { symbol: "ص", english: "Saad", sound_path: "/sounds/arabic/Saad.mp3" },
  { symbol: "ض", english: "Daad", sound_path: "/sounds/arabic/Daad.mp3" },
  { symbol: "ط", english: "Taa", sound_path: "/sounds/arabic/Taa.mp3" },
  { symbol: "ظ", english: "Zaa", sound_path: "/sounds/arabic/Zaa.mp3" },
  { symbol: "ع", english: "Ayn", sound_path: "/sounds/arabic/Ayn.mp3" },
  { symbol: "غ", english: "Ghayn", sound_path: "/sounds/arabic/Ghayn.mp3" },
  { symbol: "ف", english: "Faa", sound_path: "/sounds/arabic/Faa.mp3" },
  { symbol: "ق", english: "Qaaf", sound_path: "/sounds/arabic/Qaaf.mp3" },
  { symbol: "ك", english: "Kaaf", sound_path: "/sounds/arabic/Kaaf.mp3" },
  { symbol: "ل", english: "Laam", sound_path: "/sounds/arabic/Laam.mp3" },
  { symbol: "م", english: "Meem", sound_path: "/sounds/arabic/Meem.mp3" },
  { symbol: "ن", english: "Noon", sound_path: "/sounds/arabic/Noon.mp3" },
  { symbol: "ه", english: "Haa", sound_path: "/sounds/arabic/Haa.mp3" },
  { symbol: "و", english: "Waw", sound_path: "/sounds/arabic/Waw.mp3" },
  { symbol: "ي", english: "Yaa", sound_path: "/sounds/arabic/Yaa.mp3" },
];
