export const cyrillicLetters = [
  { symbol: "А", english: "A", sound_path: "/sounds/cyrillic/pronunciation_ru_а.mp3" },
  { symbol: "Б", english: "B", sound_path: "/sounds/cyrillic/pronunciation_ru_б.mp3" },
  { symbol: "В", english: "V", sound_path: "/sounds/cyrillic/pronunciation_ru_в.mp3" },
  { symbol: "Г", english: "G", sound_path: "/sounds/cyrillic/pronunciation_ru_г.mp3" },
  { symbol: "Д", english: "D", sound_path: "/sounds/cyrillic/pronunciation_ru_д.mp3" },
  { symbol: "Е", english: "E", sound_path: "/sounds/cyrillic/pronunciation_ru_е.mp3" },
  { symbol: "Ё", english: "Yo", sound_path: "/sounds/cyrillic/pronunciation_ru_ё.mp3" },
  { symbol: "Ж", english: "Zh", sound_path: "/sounds/cyrillic/pronunciation_ru_ж.mp3" },
  { symbol: "З", english: "Z", sound_path: "/sounds/cyrillic/pronunciation_uk_з.mp3" },
  { symbol: "И", english: "I", sound_path: "/sounds/cyrillic/pronunciation_ru_и.mp3" },
  { symbol: "Й", english: "Y", sound_path: "/sounds/cyrillic/pronunciation_ru_й.mp3" },
  { symbol: "К", english: "K", sound_path: "/sounds/cyrillic/pronunciation_ru_к.mp3" },
  { symbol: "Л", english: "L", sound_path: "/sounds/cyrillic/pronunciation_uk_л.mp3" },
  { symbol: "М", english: "M", sound_path: "/sounds/cyrillic/pronunciation_ru_м.mp3" },
  { symbol: "Н", english: "N", sound_path: "/sounds/cyrillic/pronunciation_ru_н.mp3" },
  { symbol: "О", english: "O", sound_path: "/sounds/cyrillic/pronunciation_ru_о.mp3" },
  { symbol: "П", english: "P", sound_path: "/sounds/cyrillic/pronunciation_be_п.mp3" },
  { symbol: "Р", english: "R", sound_path: "/sounds/cyrillic/pronunciation_ru_р.mp3" },
  { symbol: "С", english: "S", sound_path: "/sounds/cyrillic/pronunciation_bg_с.mp3" },
  { symbol: "Т", english: "T", sound_path: "/sounds/cyrillic/pronunciation_ru_т.mp3" },
  { symbol: "У", english: "U", sound_path: "/sounds/cyrillic/pronunciation_ru_у.mp3" },
  { symbol: "Ф", english: "F", sound_path: "/sounds/cyrillic/pronunciation_uk_ф.mp3" },
  { symbol: "Х", english: "Kh", sound_path: "/sounds/cyrillic/pronunciation_ru_х.mp3" },
  { symbol: "Ц", english: "Ts", sound_path: "/sounds/cyrillic/pronunciation_uk_ц.mp3" },
  { symbol: "Ч", english: "Ch", sound_path: "/sounds/cyrillic/pronunciation_uk_ч.mp3" },
  { symbol: "Ш", english: "Sh", sound_path: "/sounds/cyrillic/pronunciation_uk_ш.mp3" },
  { symbol: "Щ", english: "Shch", sound_path: "/sounds/cyrillic/pronunciation_uk_щ.mp3" },
  { symbol: "Ъ", english: "Hard sign", sound_path: "/sounds/cyrillic/pronunciation_ru_ъ.mp3" },
  { symbol: "Ы", english: "Y", sound_path: "/sounds/cyrillic/pronunciation_ru_ы.mp3" },
  { symbol: "Ь", english: "Soft sign", sound_path: "/sounds/cyrillic/pronunciation_ru_ь.mp3" },
  { symbol: "Э", english: "E", sound_path: "/sounds/cyrillic/pronunciation_ru_э.mp3" },
  { symbol: "Ю", english: "Yu", sound_path: "/sounds/cyrillic/pronunciation_uk_ю.mp3" },
  { symbol: "Я", english: "Ya", sound_path: "/sounds/cyrillic/pronunciation_uk_я.mp3" },
];
