export const greekLetters = [
  { symbol: "α", english: "A", sound_path: "/sounds/greek/pronunciation_el_α.mp3" },
  { symbol: "β", english: "B", sound_path: "/sounds/greek/pronunciation_grc_β.mp3" },
  { symbol: "γ", english: "G", sound_path: "/sounds/greek/pronunciation_grc_γ.mp3" },
  { symbol: "δ", english: "D", sound_path: "/sounds/greek/pronunciation_grc_delta.mp3" },
  { symbol: "ε", english: "E", sound_path: "/sounds/greek/pronunciation_el_e.mp3" },
  { symbol: "ζ", english: "Z", sound_path: "/sounds/greek/pronunciation_el_ζ_ζ.mp3" },
  { symbol: "η", english: "H", sound_path: "/sounds/greek/pronunciation_grc_η.mp3" },
  { symbol: "θ", english: "Th", sound_path: "/sounds/greek/pronunciation_grc_θ.mp3" },
  { symbol: "ι", english: "I", sound_path: "/sounds/greek/pronunciation_el_ι.mp3" },
  { symbol: "κ", english: "K", sound_path: "/sounds/greek/pronunciation_grc_κ.mp3" },
  { symbol: "λ", english: "L", sound_path: "/sounds/greek/pronunciation_el_λ.mp3" },
  { symbol: "μ", english: "M", sound_path: "/sounds/greek/pronunciation_grc_μ.mp3" },
  { symbol: "ν", english: "N", sound_path: "/sounds/greek/pronunciation_grc_ν.mp3" },
  { symbol: "ξ", english: "X", sound_path: "/sounds/greek/pronunciation_grc_ξ.mp3" },
  { symbol: "ο", english: "O", sound_path: "/sounds/greek/pronunciation_grc_ο.mp3" },
  { symbol: "π", english: "P", sound_path: "/sounds/greek/pronunciation_grc_π.mp3" },
  { symbol: "ρ", english: "R", sound_path: "/sounds/greek/pronunciation_grc_ro.mp3" },
  { symbol: "σ", english: "S", sound_path: "/sounds/greek/pronunciation_grc_σ.mp3" },
  { symbol: "τ", english: "T", sound_path: "/sounds/greek/pronunciation_grc_τ.mp3" },
  { symbol: "υ", english: "Y", sound_path: "/sounds/greek/pronunciation_grc_υ.mp3" },
  { symbol: "φ", english: "Ph", sound_path: "/sounds/greek/pronunciation_grc_φ.mp3" },
  { symbol: "χ", english: "Ch", sound_path: "/sounds/greek/pronunciation_grc_χ.mp3" },
  { symbol: "ψ", english: "Ps", sound_path: "/sounds/greek/pronunciation_grc_ψ.mp3" },
  { symbol: "ω", english: "O", sound_path: "/sounds/greek/pronunciation_grc_ω.mp3" },
];
