export const hangulLetters = [
  { symbol: "가", english: "ga", sound_path: "/sounds/hangul/pronunciation_ko_ga.mp3" },
  { symbol: "나", english: "na", sound_path: "/sounds/hangul/pronunciation_ko_na.mp3" },
  { symbol: "다", english: "da", sound_path: "/sounds/hangul/pronunciation_ko_da.mp3" },
  { symbol: "라", english: "ra", sound_path: "/sounds/hangul/pronunciation_ko_ra.mp3" },
  { symbol: "마", english: "ma", sound_path: "/sounds/hangul/pronunciation_ko_ma.mp3" },
  { symbol: "바", english: "ba", sound_path: "/sounds/hangul/pronunciation_ko_ba.mp3" },
  { symbol: "사", english: "sa", sound_path: "/sounds/hangul/pronunciation_ko_sa.mp3" },
  { symbol: "아", english: "a", sound_path: "/sounds/hangul/pronunciation_ko_a.mp3" },
  { symbol: "자", english: "ja", sound_path: "/sounds/hangul/p_ko_ja.mp3" },
  { symbol: "차", english: "ca", sound_path: "/sounds/hangul/pronunciation_ko_cha.mp3" },
  { symbol: "카", english: "ka", sound_path: "/sounds/hangul/p_ko_ka.mp3" },
  { symbol: "타", english: "ta", sound_path: "/sounds/hangul/p_ko_ta.mp3" },
  { symbol: "파", english: "pa", sound_path: "/sounds/hangul/p_ko_pa.mp3" },
  { symbol: "하", english: "ha", sound_path: "/sounds/hangul/p_ko_ha.mp3" },
  { symbol: "거", english: "geo", sound_path: "/sounds/hangul/p_ko_beo.mp3" },
  { symbol: "너", english: "neo", sound_path: "/sounds/hangul/p_ko_neo.mp3" },
  { symbol: "더", english: "deo", sound_path: "/sounds/hangul/p_ko_deo.mp3" },
  { symbol: "러", english: "reo", sound_path: "/sounds/hangul/p_ko_reo.mp3" },
  { symbol: "머", english: "meo", sound_path: "/sounds/hangul/p_ko_meo.mp3" },
  { symbol: "버", english: "beo", sound_path: "/sounds/hangul/p_ko_beo.mp3" },
  { symbol: "서", english: "seo", sound_path: "/sounds/hangul/p_ko_seo.mp3" },
  { symbol: "어", english: "eo", sound_path: "/sounds/hangul/p_ko_eo.mp3" },
  { symbol: "저", english: "jeo", sound_path: "/sounds/hangul/p_ko_jeo.mp3" },
  { symbol: "처", english: "ceo", sound_path: "/sounds/hangul/p_ko_ceo.mp3" },
];
