import kroman from "kroman";
export const hangulLetters = [
  { symbol: "가", english: kroman.parse("가"), sound_path: "/sounds/hangul/pronunciation_ko_ga.mp3" },
  { symbol: "나", english: kroman.parse("나"), sound_path: "/sounds/hangul/pronunciation_ko_na.mp3" },
  { symbol: "다", english: kroman.parse("다"), sound_path: "/sounds/hangul/pronunciation_ko_da.mp3" },
  { symbol: "라", english: kroman.parse("라"), sound_path: "/sounds/hangul/pronunciation_ko_ra.mp3" },
  { symbol: "마", english: kroman.parse("마"), sound_path: "/sounds/hangul/pronunciation_ko_ma.mp3" },
  { symbol: "바", english: kroman.parse("바"), sound_path: "/sounds/hangul/pronunciation_ko_ba.mp3" },
  { symbol: "사", english: kroman.parse("사"), sound_path: "/sounds/hangul/pronunciation_ko_sa.mp3" },
  { symbol: "아", english: kroman.parse("아"), sound_path: "/sounds/hangul/pronunciation_ko_a.mp3" },
  { symbol: "자", english: kroman.parse("자"), sound_path: "/sounds/hangul/p_ko_ja.mp3" },
  { symbol: "차", english: kroman.parse("차"), sound_path: "/sounds/hangul/pronunciation_ko_cha.mp3" },
  { symbol: "카", english: kroman.parse("카"), sound_path: "/sounds/hangul/p_ko_ka.mp3" },
  { symbol: "타", english: kroman.parse("타"), sound_path: "/sounds/hangul/p_ko_ta.mp3" },
  { symbol: "파", english: kroman.parse("파"), sound_path: "/sounds/hangul/p_ko_pa.mp3" },
  { symbol: "하", english: kroman.parse("하"), sound_path: "/sounds/hangul/p_ko_ha.mp3" },
  { symbol: "거", english: kroman.parse("거"), sound_path: "/sounds/hangul/p_ko_beo.mp3" },
  { symbol: "너", english: kroman.parse("너"), sound_path: "/sounds/hangul/p_ko_neo.mp3" },
  { symbol: "더", english: kroman.parse("더"), sound_path: "/sounds/hangul/p_ko_deo.mp3" },
  { symbol: "러", english: kroman.parse("러"), sound_path: "/sounds/hangul/p_ko_reo.mp3" },
  { symbol: "머", english: kroman.parse("머"), sound_path: "/sounds/hangul/p_ko_meo.mp3" },
  { symbol: "버", english: kroman.parse("버"), sound_path: "/sounds/hangul/p_ko_beo.mp3" },
  { symbol: "서", english: kroman.parse("서"), sound_path: "/sounds/hangul/p_ko_seo.mp3" },
  { symbol: "어", english: kroman.parse("어"), sound_path: "/sounds/hangul/p_ko_eo.mp3" },
  { symbol: "저", english: kroman.parse("저"), sound_path: "/sounds/hangul/p_ko_jeo.mp3" },
  { symbol: "처", english: kroman.parse("처"), sound_path: "/sounds/hangul/p_ko_ceo.mp3" },
];
