// Hiragana
export const hiraganaLetters = [
  { symbol: "あ", english: "a", sound_path: "/sounds/hiragana/a.mp3" },
  { symbol: "い", english: "i", sound_path: "/sounds/hiragana/i.mp3" },
  { symbol: "う", english: "u", sound_path: "/sounds/hiragana/u.mp3" },
  { symbol: "え", english: "e", sound_path: "/sounds/hiragana/e.mp3" },
  { symbol: "お", english: "o", sound_path: "/sounds/hiragana/o.mp3" },
  { symbol: "か", english: "ka", sound_path: "/sounds/hiragana/ka.mp3" },
  { symbol: "き", english: "ki", sound_path: "/sounds/hiragana/ki.mp3" },
  { symbol: "く", english: "ku", sound_path: "/sounds/hiragana/ku.mp3" },
  { symbol: "け", english: "ke", sound_path: "/sounds/hiragana/ke.mp3" },
  { symbol: "こ", english: "ko", sound_path: "/sounds/hiragana/ko.mp3" },
  { symbol: "さ", english: "sa", sound_path: "/sounds/hiragana/sa.mp3" },
  { symbol: "し", english: "shi", sound_path: "/sounds/hiragana/shi.mp3" },
  { symbol: "す", english: "su", sound_path: "/sounds/hiragana/su.mp3" },
  { symbol: "せ", english: "se", sound_path: "/sounds/hiragana/se.mp3" },
  { symbol: "そ", english: "so", sound_path: "/sounds/hiragana/so.mp3" },
  { symbol: "た", english: "ta", sound_path: "/sounds/hiragana/ta.mp3" },
  { symbol: "ち", english: "chi", sound_path: "/sounds/hiragana/chi.mp3" },
  { symbol: "つ", english: "tsu", sound_path: "/sounds/hiragana/tsu.mp3" },
  { symbol: "て", english: "te", sound_path: "/sounds/hiragana/te.mp3" },
  { symbol: "と", english: "to", sound_path: "/sounds/hiragana/to.mp3" },
  { symbol: "な", english: "na", sound_path: "/sounds/hiragana/na.mp3" },
  { symbol: "に", english: "ni", sound_path: "/sounds/hiragana/ni.mp3" },
  { symbol: "ぬ", english: "nu", sound_path: "/sounds/hiragana/nu.mp3" },
  { symbol: "ね", english: "ne", sound_path: "/sounds/hiragana/ne.mp3" },
  { symbol: "の", english: "no", sound_path: "/sounds/hiragana/no.mp3" },
  { symbol: "は", english: "ha", sound_path: "/sounds/hiragana/ha.mp3" },
  { symbol: "ひ", english: "hi", sound_path: "/sounds/hiragana/hi.mp3" },
  { symbol: "ふ", english: "fu", sound_path: "/sounds/hiragana/fu.mp3" },
  { symbol: "へ", english: "he", sound_path: "/sounds/hiragana/he.mp3" },
  { symbol: "ほ", english: "ho", sound_path: "/sounds/hiragana/ho.mp3" },
  { symbol: "ま", english: "ma", sound_path: "/sounds/hiragana/ma.mp3" },
  { symbol: "み", english: "mi", sound_path: "/sounds/hiragana/mi.mp3" },
  { symbol: "む", english: "mu", sound_path: "/sounds/hiragana/mu.mp3" },
  { symbol: "め", english: "me", sound_path: "/sounds/hiragana/me.mp3" },
  { symbol: "も", english: "mo", sound_path: "/sounds/hiragana/mo.mp3" },
  { symbol: "や", english: "ya", sound_path: "/sounds/hiragana/ya.mp3" },
  { symbol: "ゆ", english: "yu", sound_path: "/sounds/hiragana/yu.mp3" },
  { symbol: "よ", english: "yo", sound_path: "/sounds/hiragana/yo.mp3" },
  { symbol: "ら", english: "ra", sound_path: "/sounds/hiragana/ra.mp3" },
  { symbol: "り", english: "ri", sound_path: "/sounds/hiragana/ri.mp3" },
  { symbol: "る", english: "ru", sound_path: "/sounds/hiragana/ru.mp3" },
  { symbol: "れ", english: "re", sound_path: "/sounds/hiragana/re.mp3" },
  { symbol: "ろ", english: "ro", sound_path: "/sounds/hiragana/ro.mp3" },
  { symbol: "わ", english: "wa", sound_path: "/sounds/hiragana/wa.mp3" },
  { symbol: "を", english: "wo", sound_path: "/sounds/hiragana/wo.mp3" }, // "wo" is often pronounced "o"
  { symbol: "ん", english: "n", sound_path: "/sounds/hiragana/n.mp3" }, // A nasal sound
];
